git:
  depth: 150
language: java
sudo: false
matrix:
  include:
    - jdk: openjdk8
      env: GRADLE_PUBLISH=true
    - jdk: openjdk11
      env: GRADLE_PUBLISH=false
install: true
script: "./gradle/buildViaTravis.sh"
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
after_success:
- "./gradlew jacocoTestReport coveralls"
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/1ffb20bef7e7580e2c93
    on_success: change
    on_failure: always
    on_start: never
env:
  global:
  - secure: MvRYIUkcecCXAyqPLJKn/k7IrhCs+N9OYzXw9g2y5U7q6MfpWjsACvJCr40Bzyje5oCCCWFPamsNKmMp5XKNtjGYVHuoD1PtN7v6HCMAreSXJ3CyCrkL0dIa8prR31iQb6j9av213+5tntT5h2ASznl7eu8zaJHSQ8gQp7NjHIE=
  - secure: JvUNXp5Hn4V1Qt7fCs7RIaySzjhY/NwHCLE/8L2V9hc4KDC+pOoITQtw4PoDAuVTH0aa8PpvGgyQGHPG9syv7d/9oBABaehEtwO7aJMHlENZH7+4cEgm1g0R3jtYZjSAaLG82QtJCTAzXN4z44nVA+w5ggP3IDGnvDkiF777N4A=
  - secure: NeRJPPxF1YqzNk3CsfofP3HRIzJh9ve+HrDzoi2gOs0ANHTfJpDK9YsnS2W3sFY3GTp1UglSSg5jgYQMEARVzNd9wWNyXT695reyjDHLRMh6G2pAMmbrcc+2yYb96KoECXwPFHhvSVM+mAJajgoW+d4ycHLUND2e9Qv4uUphFKg=
  - secure: Adgy49csuecA1INU3A4xZ00krJzPvNXYWQ/Oj47/oGbnSA1lTtSAP3qBn2p3DRDdFfQdNljLUgivZlLS0tkjvDHCD0tsTLJ33Z5620rtPAUAMR7HI7mMwbJq2arpDBNzKpGW0AOrXvhF2RjCvPpr5XMbAaxrtbDGZe5eUsKZGBk=
  - secure: dLAi1PdE4o/I+wbKqpFcYGA4qjBMGtOTqoEAEJ3t9cDM3CjSBNqIa6vB/D5XP5qUem7p1ZmypHm1cC74dwkQyKwxhfcdYdBNaQGV2c7sBeVEeyFuuwuq6Ud2KJ8MPtNQIRnDZFv5OpIxxAFaz9qGea4Cb+CpZLln5yanIEh1Fm8=
  - secure: dGdSpiUAf15zsuOBf2VXR6le3mgYLDuvPWllpVJDDYjjlQD0UsIWRaunOHgKKrmbNrLzOcKdo98t4WGbixFFdHB6kIVjAoJAao0+lBYAAxO7FTUuaM2e1ksoVlH+FPy3zegteNDpijmRbiXl540c+tDQbX0QM+OnOQqRSqnSReM=
